# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/leeea/final_project/final_project.srcs/sources_1/ip/wall_nut/wall_nut.xci
# IP: The module: 'wall_nut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/leeea/final_project/final_project.srcs/sources_1/ip/wall_nut/wall_nut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wall_nut'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/leeea/final_project/final_project.srcs/sources_1/ip/wall_nut/wall_nut.xci
# IP: The module: 'wall_nut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/leeea/final_project/final_project.srcs/sources_1/ip/wall_nut/wall_nut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wall_nut'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
